### ISSUE TITLE
Share/publish course schedule

### ISSUE THREAD

**Issue by arezaii** [LEAF-BoiseState/GEOS-518-HydrologicModeling#4]
Currently the link on the course website for viewing the schedule gives students this response:
![image](https://user-images.githubusercontent.com/2806014/64445241-3c2f1800-d093-11e9-90ea-2dce9e2a89fa.png)

**Comment by LejoFlores** [comment]
Try again if you can. I fixed it and tried with safari. It should work now.

**Comment by arezaii** [comment]
confirmed working for me
