### ISSUE TITLE
Share/publish reading list

### ISSUE THREAD

**Issue by arezaii** [LEAF-BoiseState/GEOS-518-HydrologicModeling#5]
Currently, students cannot access the reading list from the website menu item "Course Readings"

![image](https://user-images.githubusercontent.com/2806014/64446535-47d00e00-d096-11e9-9ff1-83e7eca24ed4.png)

**Comment by LejoFlores** [comment]
Fixed this and verified it worked with different browser. Let me know if it works or not.

**Comment by arezaii** [comment]
confirmed I can see the reading list
