### ISSUE TITLE
Share/publish week 1 slides

### ISSUE THREAD

**Issue by arezaii** [LEAF-BoiseState/GEOS-518-HydrologicModeling#7]
Currently, students clicking on the "Course Slides" menu item receive the following message:

![image](https://user-images.githubusercontent.com/2806014/64448492-11e15880-d09b-11e9-9d57-639396381ccb.png)

**Comment by LejoFlores** [comment]
Try again. Tried to add view permissions.

**Comment by arezaii** [comment]
confirmed I can see the slides
